apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: multi-window-burn-rate
  labels:
    prometheus: k8s
spec:
  groups:
  - name: burn-rate-alerts
    rules:
    # 1h fast burn rate
    - alert: HighErrorRate1h
      expr: |
        job:request_error_rate5m > 14.4 * 0.01 
        and
        job:request_error_rate1h > 14.4 * 0.01
      labels:
        severity: page
      annotations:
        summary: "High error rate over 1h (Fast burn)"
    
    # 6h slow burn rate
    - alert: HighErrorRate6h
      expr: |
        job:request_error_rate30m > 6 * 0.01
        and
        job:request_error_rate6h > 6 * 0.01
      labels:
        severity: ticket
      annotations:
        summary: "High error rate over 6h (Slow burn)"
