apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: email-config
  namespace: demo
  labels:
    release: kube-prometheus-stack
spec:
  route:
    groupBy: ['alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'email-receiver'
    matchers:
    - name: severity
      matchType: =
      value: critical
  receivers:
  - name: 'email-receiver'
    emailConfigs:
    - to: 'thanhtrung8ctv@gmail.com'
      from: 'thanhtrung8ctv@gmail.com'
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'thanhtrung8ctv@gmail.com'
      authPassword:
        name: email-smtp-secret
        key: password
